export default {
    COLUMN_CREATE: 'COLUMN_CREATE',
    COLUMN_UPDATE: 'COLUMN_UPDATE',
    COLUMN_DELETE: 'COLUMN_DELETE',

    GROUP_CREATE: 'GROUP_CREATE',
    GROUP_UPDATE: 'GROUP_UPDATE',
    GROUP_DELETE: 'GROUP_DELETE',

    CARD_CREATE: 'CARD_CREATE',
    CARD_UPDATE: 'CARD_UPDATE',
    CARD_DELETE: 'CARD_DELETE',
}
